kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: test-terron-cluster
nodes:
  - role: control-plane
  - role: control-plane
  - role: control-plane
  - role: worker
  - role: worker
  - role: worker
